ENoticeBoard/ENoticeBoard/Controllers/TargetsController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace ENoticeBoard.Controllers
{
    public class TargetsController : Controller
    {
        private readonly MyDatabaseEntities _db = new MyDatabaseEntities();

        // GET: Targets
        public ActionResult Index()
        {
            return View(_db.Targets.AsNoTracking().ToList());
        }

        // GET: Targets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Target target = _db.Targets.Find(id);
            if (target == null)
            {
                return HttpNotFound();
            }
            return View(target);
        }

        // GET: Targets/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Targets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TargetId,Subject,TargetNum")] Target target)
        {
            if (ModelState.IsValid)
            {
                _db.Targets.Add(target);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(target);
        }

        // GET: Targets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Target target = _db.Targets.Find(id);
            if (target == null)
            {
                return HttpNotFound();
            }
            return View(target);
        }

        // POST: Targets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TargetId,Subject,TargetNum")] Target target)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(target).State = EntityState.Modified;
                _db.SaveChanges();
                return PartialView("_Success");
            }
            return PartialView("Edit",target);
        }

        // GET: Targets/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Target target = _db.Targets.Find(id);
            if (target == null)
            {
                return HttpNotFound();
            }
            return View(target);
        }

        // POST: Targets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Target target = _db.Targets.Find(id);
            if (target != null) _db.Targets.Remove(target);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ENoticeBoard/ENoticeBoard/Views/Targets/Create.cshtml
@model Target

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.TargetId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TargetId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TargetId, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.TargetNum, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TargetNum, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TargetNum, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

ENoticeBoard/ENoticeBoard/Views/Targets/Delete.cshtml
@model Target

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    </head>
<body>
    
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Subject)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Subject)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.TargetNum)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.TargetNum)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> 
            </div>
        }
    
</body>
</html>

ENoticeBoard/ENoticeBoard/Views/Targets/Details.cshtml
@model Target

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Subject)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Subject)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.TargetNum)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.TargetNum)
            </dd>
    
        </dl>
    </div>
    
</body>
</html>

ENoticeBoard/ENoticeBoard/Views/Targets/Edit.cshtml
@model Target

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @using (Html.BeginForm("Edit", "Targets", FormMethod.Post, new { @id = "Target" }))
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <div class="container-fluid">
            @Html.ValidationSummary(true, "", new {@class = "text-danger"})
            @Html.HiddenFor(model => model.TargetId)

            <div class="form-group">
                @Html.LabelFor(model => model.Subject)
                @Html.EditorFor(model => model.Subject, new {htmlAttributes = new {@class = "form-control DisabledText" } })
                @Html.ValidationMessageFor(model => model.Subject, "", new {@class = "text-danger"})
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TargetNum)
                @Html.EditorFor(model => model.TargetNum, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.TargetNum, "", new {@class = "text-danger"})
            </div>
            </div>
            <div>
                <input type="submit" value="Save" class="btn btn-success"/>
            </div>
        </div>
    }
    
    
</body>
</html>
<script>
    $('.DisabledText').keydown(function (event) {

        var key = (event.which) ? event.which : event.keyCode;
        if (key === 8 || key === 46) {
            event.preventDefault();
            return false;
        } else {
            event.preventDefault();
            return false;
        }
    });

</script>

ENoticeBoard/ENoticeBoard/Views/Targets/Index.cshtml
@model IEnumerable<Target>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Subject)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TargetNum)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Subject)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TargetNum)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.TargetId }) |
                @Html.ActionLink("Details", "Details", new { id=item.TargetId }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.TargetId })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>

ENoticeBoard/ENoticeBoard/Views/Targets/_Success.cshtml
@model dynamic

<label>Success!</label>

<script>
    setTimeout(function() {
        $('#userModal').modal('hide');
        location.reload();
    }, 1000);
</script>