ENoticeBoard/ENoticeBoard/Controllers/BreakagesController.cs
using ENoticeBoard.Models;
using ENoticeBoard.ViewModels;
using System;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace ENoticeBoard.Controllers
{
    public class BreakagesController : Controller
    {
        private readonly MyDatabaseEntities _db = new MyDatabaseEntities();
        private static readonly BaseDataEntities BaseData = new BaseDataEntities();

        // GET: Breakages
        [HttpPost]
        public PartialViewResult Summary(string period,string year)
        {
            if(period==null && year==null)
            {
                period= DateConversion.CurrentPeriod();
                year = DateConversion.CurrentYear();
            }

            var publishedDate = DateConversion.PublishedDate();
            ViewBag.breakage = _db.Targets.AsNoTracking().Single(t => t.Subject == "Breakage").TargetNum;
            var model = new BreakageSummaryViewFormModel()
            {
                BreakageWFPs = _db.Vw_BreakagesWithinFinancialPeriod.AsNoTracking().Where(x=>x.FinancialPeriod==period && x.FinancialYear==year && x.isDeleted==false).ToList(),
                GroupByModels = _db.Vw_BreakagesWithinFinancialPeriod.AsNoTracking().Where(x=>x.FinancialPeriod==period && x.FinancialYear==year && x.isDeleted==false)
                    .GroupBy(x => new {x.FinancialPeriod, x.FinancialYear}).Select(y => new GroupByModel()
                    {
                        Period = y.Key.FinancialPeriod, Year = y.Key.FinancialYear,
                        Sum = y.Sum(z => z.Cost)
                    }).ToList(),
                Periodddl = BaseData.FinancialCalendars.AsNoTracking().Select(x=>new DropDownBoxList()
                {
                    text=x.FinancialPeriod,
                    value=x.FinancialPeriod
                }).Distinct().OrderBy(x=>x.value).ToList(),
                Yearddl = BaseData.FinancialCalendars.AsNoTracking().Where(x=>x.Date >= publishedDate).Select(x=>new DropDownBoxList()
                {
                    text=x.FinancialYear,
                    value=x.FinancialYear
                }).Distinct().OrderBy(x=>x.value).ToList(),
                selectedPeriod = period,
                selectedYear = year
                
            };

            
           
         
            return PartialView(model);
        }

        
        // GET: Breakages/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Breakage breakage = _db.Breakages.Find(id);
            if (breakage == null)
            {
                return HttpNotFound();
            }
            
            var model = new BreakageFormViewModel()
            {
                Id= breakage.BreakageId,
                Subject = breakage.Subject,
                Date = breakage.Date,
                SiteId = breakage.Site,
                Cost = breakage.Cost,
                TypeId = breakage.Type,
                Sites = _db.Sites.AsNoTracking().ToList(),
                Types = _db.BreakageTypes.AsNoTracking().ToList()
                
                
            };
            

            return PartialView(model);
        }

        // GET: Breakages/Create
        public ActionResult Create()
        {
            var model = new BreakageFormViewModel
            {
                Date = DateTime.Today,
                Sites = _db.Sites.AsNoTracking().ToList(),
                Types = _db.BreakageTypes.AsNoTracking().ToList()
                    
            };
            return PartialView(model);
        }

        // POST: Breakages/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public JsonResult Create(BreakageFormViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                viewModel.Sites = _db.Sites.AsNoTracking().ToList();
                viewModel.Types = _db.BreakageTypes.AsNoTracking().ToList();
                
            }

            var breakage = new Breakage
            {
                BreakageId= viewModel.Id,
                Subject = viewModel.Subject,
                Date = viewModel.Date,
                Site = viewModel.SiteId,
                Cost = viewModel.Cost,
                Type = viewModel.TypeId,
                isDeleted = false
            };

            _db.Breakages.Add(breakage);
            _db.SaveChanges();


            return Json("Success", JsonRequestBehavior.AllowGet);
        }

        // GET: Breakages/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Breakage breakage = _db.Breakages.Find(id);
            if (breakage == null)
            {
                return HttpNotFound();
            }
            
            var model = new BreakageFormViewModel()
            {
                Id= breakage.BreakageId,
                Subject = breakage.Subject,
                Date = breakage.Date,
                SiteId = breakage.Site,
                Cost = breakage.Cost,
                TypeId = breakage.Type,
                Sites = _db.Sites.AsNoTracking().ToList(),
                Types = _db.BreakageTypes.AsNoTracking().ToList()
                
                
            };
            

            return PartialView(model);
        }

        // POST: Breakages/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Edit(BreakageFormViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                Breakage breakage = _db.Breakages.Find(viewModel.Id);
                if (breakage == null)
                {
                    return HttpNotFound();
                }

                breakage.Subject = viewModel.Subject;
                breakage.Date = viewModel.Date;
                breakage.Site = viewModel.SiteId;
                breakage.Cost = viewModel.Cost;
                breakage.Type = viewModel.TypeId;
                
                _db.SaveChanges();
                
            }
            return Json("success", JsonRequestBehavior.AllowGet);
        }

        //// GET: Breakages/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Breakage breakage = db.Breakages.Find(id);
        //    if (breakage == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(breakage);
        //}

        //// POST: Breakages/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Breakage breakage = db.Breakages.Find(id);
        //    db.Breakages.Remove(breakage);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Breakage breakage = _db.Breakages.Find(id);
            if (breakage == null)
            {
                return HttpNotFound();
            }
            
            var model = new BreakageFormViewModel()
            {
                Id= breakage.BreakageId,
                Subject = breakage.Subject,
                Date = breakage.Date,
                SiteId = breakage.Site,
                Cost = breakage.Cost,
                TypeId = breakage.Type,
                Sites = _db.Sites.AsNoTracking().ToList(),
                Types = _db.BreakageTypes.AsNoTracking().ToList()
                
                
            };
            

            return PartialView(model);
        }

        [HttpPost]
        public JsonResult DeleteConfirmed(int? id)
        {
            Breakage breakage = _db.Breakages.Find(id);
            if (breakage != null)
            {
                breakage.isDeleted = true;
            }

            _db.SaveChanges();
            return Json("success", JsonRequestBehavior.AllowGet);
            
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ENoticeBoard/ENoticeBoard/Views/Breakages/Create.cshtml
@using BreakageFormViewModel = ENoticeBoard.ViewModels.BreakageFormViewModel
@model BreakageFormViewModel

@{
    ViewBag.Title = "Create";
}


<form id="createBrk">
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        <div class="col-md-12 form-horizontal">

            <div class="form-group">
                @Html.LabelFor(model => model.Subject)

                @Html.EditorFor(model => model.Subject, new {htmlAttributes = new {@class = "form-control" }})
                @Html.ValidationMessageFor(model => model.Subject, "", new {@class = "text-danger"})

            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Date)
                @Html.TextBoxFor(model => model.Date, "{0:dd/MM/yyyy}", new {@class = "form-control", Type = "DateTime"})
                @Html.ValidationMessageFor(model => model.Date, "", new {@class = "text-danger"})

            </div>

            <div class="form-group">
                <label>Site</label>

                @Html.DropDownListFor(m => m.SiteId, new SelectList(Model.Sites, "SiteId", "Subject"), "", new {@class = "form-control"})
                @Html.ValidationMessageFor(m => m.SiteId)
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Cost)
                <div class="input-group">
                    <div class="input-group-addon">$</div>
                    @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control pull-right", @type = "number", @dir = "rtl" } })
                    @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">

                <label>Type</label>
                @Html.DropDownListFor(m => m.TypeId, new SelectList(Model.Types, "TypeId", "Subject"), "", new {@class = "form-control"})
                @Html.ValidationMessageFor(m => m.TypeId)
            </div>
        </div>
        <div>
            <button type="button" id="btnSaveBrk" value="Save" class="btn btn-success">Save</button>
            
        </div>
    </div>

</form>

<script type="text/javascript">

    $(document).ready(function() {
        $(".formattedNumberField").on('input propertychange paste change', function (evt) {
            if (evt.which !== 110 && $(this).val() !== "") {
                var n = parseFloat($(this).val().replace(/\,/g, ''), 10);
                $(this).val(n.toLocaleString());
            }
        });

    });

    $('input[type=datetime]').datepicker({
        dateFormat: "dd/mm/yy",
        changeMonth: true,
        changeYear: true,
        maxDate:0,
        yearRange: "-2:+10"
    });
   

    $('#btnSaveBrk').click(function() {
        if ($("#Subject").val().trim() === "" ||
            $("#Date").val().trim() === "" ||
            $("#SiteId").val().trim() === "" ||
            $("#Cost").val().trim() === "" ||
            $("#TypeId").val().trim() === "") {
            alert("All fields are required");
            return;
        }
        if ($("#Subject").val().length >100) {
            alert("Subject is too long");
            return;
        }
        else {
            var s = moment($('#Date').val(), "DD/MM/YYYY", true);
            var isValid = s.isValid();
            if (isValid === false) {
                alert("Invalid date format: " + $('#Date').val());
                return;
            }
        }
        var $this = $("#createBrk");
        var dataToSend = $this.serialize();
        console.log(dataToSend);
        $.ajax({
            type: "POST",
            url: '@Url.Action("Create", "Breakages")',
            dataType: 'json',
            data: dataToSend,
            success: function() {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Summary", "Breakages")',
                    dataType: 'html',
                    success: function(data) {
                        $("#createModal").modal('hide');
                        $('#setModalTitle').html("Breakage");
                        $("#PanelModalBody").html(data);
                        $("#PanelModal").modal('show');
                    },

                    error: function(data) {
                        console.log(data);
                    }
                });
                @*$.ajax({
                    type: "GET",
                    url: '@Url.Action("GetSumBreakage", "Home")',
                    dataType: 'json',
                    success: function(data) {
                        $("#BreakageSum").html("$ " +data);
                    },
                    error: function() {
                        alert("Get Failed");
                    }
                });*@


            },
            error: function(data) {
                console.log(data);
            }
        });
    });

</script>

ENoticeBoard/ENoticeBoard/Views/Breakages/Delete.cshtml
@using BreakageFormViewModel = ENoticeBoard.ViewModels.BreakageFormViewModel
@model BreakageFormViewModel
<style type="text/css">
    .dl-horizontal dt {
        text-align: left;
        width: auto;
    }

    .dl-horizontal dd {
        margin-left: 100px;
    }
</style>

<div>
    <dl class="dl-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        <dt>
            @Html.DisplayNameFor(model => model.Subject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Model.Date.ToShortDateString()
        </dd>

        <dt>
            Site
        </dt>

        <dd>
            @foreach (var site in Model.Sites)
            {
                if (site.SiteId == Model.SiteId)
                {
                    @site.Subject
                }
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cost)
        </dd>

        <dt>
            Type
        </dt>

        <dd>
            @foreach (var type in Model.Types)
            {
                if (type.TypeId == Model.TypeId)
                {
                    @type.Subject
                }
            }
        </dd>

    </dl>

    @using (Html.BeginForm())
    {


        <div class="form-group">
            <input type="button" id="btnDeleteBreakage" value="Delete" class="btn btn-primary" />

        </div>
    }
</div>


<script>
    $('#btnDeleteBreakage').click(function() {
        var id = $("#Id").val();


        $.ajax({
            type: "POST",
            url: '@Url.Action("DeleteConfirmed", "Breakages")',
            dataType: 'json',
            data: { "id" : id },
            success: function (data) {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Summary", "Breakages")',
                    dataType: 'html',
                    success: function (data) {
                        $('#setModalTitle').html("Brekage");
                        $("#PanelModalBody").html(data);
                        $("#PanelModal").modal('show');
                    },
                    error: function(data) {
                        console.log(data);
                    }
                });

                $('#deleteModal')
                    .modal('hide')
                    .on('hidden.bs.modal', function (e) {
                        $('#PanelModal').modal('show');

                        $(this).off('hidden.bs.modal'); // Remove the 'on' event binding
                    });
            },
            error: function(data) {
                console.log(data);
            }
        });
    });
</script>

ENoticeBoard/ENoticeBoard/Views/Breakages/Edit.cshtml
@using BreakageFormViewModel = ENoticeBoard.ViewModels.BreakageFormViewModel
@model BreakageFormViewModel

@{
    ViewBag.Title = "Edit";
}





<form id="frmEditBrk">
    <div class="form-horizontal">
        <div class="col-md-12">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.Subject)
                <div>
                    @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                    @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Date)
                <div>
                    @Html.TextBoxFor(model => model.Date, "{0:dd/MM/yyyy}", new { @class = "form-control", @Type = "DateTime" })
                    @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label>Site</label>
                <div>
                    @Html.DropDownListFor(m => m.SiteId, new SelectList(Model.Sites, "SiteId", "Subject"), new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.SiteId)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Cost)
                <div class="input-group">
                    <div class="input-group-addon">$</div>
                    @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control pull-right", @type = "number", @dir = "rtl" } })
                    @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label>Type</label>
                <div>
                    @Html.DropDownListFor(m => m.TypeId, new SelectList(Model.Types, "TypeId", "Subject"), new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.TypeId)
                </div>
            </div>
        </div>
        <button type="button" id="btnSaveBrk" value="Save" class="btn btn-success">Save</button>

    </div>
</form>

<script type="text/javascript">
        $('input[type=datetime]').datepicker({
            dateFormat: "dd/mm/yy",
            changeMonth: true,
            changeYear: true,
            maxDate:0,
            yearRange: "-2:+10"
        });
        $('#btnSaveBrk').click(function () {
            if ($("#Subject").val().trim() === "" ||
                $("#Date").val().trim() === "" ||
                $("#Cost").val().trim() === "")
            {
                alert("All fields are required");
                return;
            }
            if ($("#Subject").val().length >100) {
                alert("Subject is too long");
                return;
            }else {
                var s = moment($('#Date').val(), "DD/MM/YYYY", true);
                var isValid = s.isValid();
                if (isValid === false) {
                    alert("Invalid date format: " + $('#Date').val());
                    return;
                }
            }
            var $this = $("#frmEditBrk");
            var dataToSend = $this.serialize();
            console.log(dataToSend);
            $.ajax({
                type: "POST",
                url: '@Url.Action("Edit", "Breakages")',
                dataType: 'json',
                data: dataToSend,
                success: function () {
                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("Summary", "Breakages")',
                        dataType: 'html',
                        success: function (data) {
                            $("#createModal").modal('hide');
                            $('#setModalTitle').html("Breakage");
                            $("#PanelModalBody").html(data);
                            $("#PanelModal").modal('show');
                        },
                        error: function(data) {
                            console.log(data);
                        }
                    });
                    @*$.ajax({
                        type: "GET",
                        url: '@Url.Action("GetSumBreakage", "Home")',
                        dataType: 'json',
                        success: function(data) {
                            $("#BreakageSum").html("$ "+data);
                        },
                        error: function() {
                            alert("Set Failed");
                        }
                    });*@
                    $('#EditModal')
                        .modal('hide')
                        .on('hidden.bs.modal', function () {
                            $('#PanelModal').modal('show');

                            $(this).off('hidden.bs.modal'); // Remove the 'on' event binding
                        });
                },
                error: function(data) {
                    console.log(data);
                }
            });
    });

</script>

ENoticeBoard/ENoticeBoard/Views/Breakages/Index.cshtml
@model IEnumerable<ENoticeBoard.Breakage>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Subject)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Site)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cost)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Type)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Subject)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Site)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cost)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Type)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.BreakageId }) |
            @Html.ActionLink("Details", "Details", new { id=item.BreakageId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.BreakageId })
        </td>
    </tr>
}

</table>

ENoticeBoard/ENoticeBoard/Views/Breakages/Summary.cshtml
@using System.Web.Mvc.Html
@using BreakageSummaryViewFormModel = ENoticeBoard.ViewModels.BreakageSummaryViewFormModel
@model BreakageSummaryViewFormModel

<head>
    <script src="~/Scripts/datetime-moment.js"></script>
    <script src="//cdn.datatables.net/plug-ins/1.10.19/sorting/date-uk.js"></script>
</head>


<form class="form-inline">
    <div class="pull-left" >
        <div class="form-group">
            <button type="button" id="btnCreateBrk" name="btnCreate" class="btn btn-default">
                <span class="glyphicon glyphicon-plus"></span> Add
            </button>
        </div>
    </div>
    <div class="pull-right">
        <div class="form-group">
            <label>Period: </label>
            @Html.DropDownListFor(m => m.selectedPeriod, new SelectList(Model.Periodddl, "Text", "Value"), new {@class = "form-control"})
        </div>
        
        <div class="form-group">
            <label>Year: </label>
            @Html.DropDownListFor(m => m.selectedYear, new SelectList(Model.Yearddl, "Text", "Value"), new { @class = "form-control" })
        </div>
        <div class="form-group">
            <button type="button" id="btnRefresh" name="btnRefresh" class= "btn btn-default" >Refresh</button>
        </div>
    </div>
   
</form>    
    

<table class="table table-bordered table-condensed table-responsive display table-striped" id="BreakageTB" style="word-wrap: normal; width: 100%">
    <thead>
    <tr>
        <th colspan="6">Breakage Target : $ @ViewBag.breakage.ToString("###,0.00")</th>
    </tr>
    <tr>
        <th style="width: 40%">
            Subject
        </th>
        <th style="width: 10%">
            Date
        </th>
        <th style="width: 10%">
            Site
        </th>
        <th style="width: 10%">
            Cost
        </th>
        <th style="width: 10%">
            Type
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.BreakageWFPs)
    {
        <tr style="text-align: center">
            <td>
                @Html.DisplayFor(modelItem => item.Subject)
            </td>
            <td>
                @item.Date.ToString("dd/MM/yyyy")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Site)
            </td>
            <td style="text-align: right">
                @item.Cost.ToString("#,###.00")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                <button rid="@item.BreakageId" name="editbtn" class="btn btn-link btn-sm Edit" aria-hidden="true">
                    <span class="glyphicon glyphicon-edit"></span>
                </button>
                <button rid="@item.BreakageId" name="detailbtn" class="btn btn-link btn-sm Detail" aria-hidden="true">
                    <span class="glyphicon glyphicon-eye-open"></span>
                </button>
                <button rid="@item.BreakageId" name="deletebtn" class="btn btn-link btn-sm Delete" aria-hidden="true">
                    <span class="glyphicon glyphicon-trash"></span>
                </button>
            </td>
        </tr>
    }
    </tbody>
</table>


<div class="modal fade" id="createModal" role="dialog">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" id="btnCloseCreate"class="close" >×</button>
                <h4 class="modal-title">Breakage</h4>
            </div>
            <div class="modal-body" id="createBody">
            </div>
        </div>

    </div>
</div>
<div class="modal fade" id="EditModal" role="dialog">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" id="btnCloseEdit">×</button>
                <h4 class="modal-title" id="myModalLabel">Breakage</h4>
            </div>
            <div class="modal-body" id="EditBody">
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="deleteModal" role="dialog">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" id="btnCloseDelete">×</button>
                <h4 class="modal-title">You want to delete this task?</h4>
            </div>
            <div class="modal-body" id="deleteBody">
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $.fn.dataTable.moment('dd/mm/yyyy');
        $('#BreakageTB').DataTable({
            autoWidth: false,
            columns: [
                { "width": "40%" },
                { "width": "10%" },
                { "width": "10%" },
                { "width": "10%" },
                { "width": "10%" },
                null
            ],
            aoColumnDefs : [
                {"aTargets" : [1], "sType" : "date-uk"}
            ]
            
        });

    });
    
    $('#btnRefresh').click(function() {
        var p = $("#selectedPeriod").val();
        var y = $('#selectedYear').val();
       
        $.ajax({
            type: "POST",
            url: '@Url.Action("Summary","Breakages")',
            datatype: "html",
            data: { "period": p, "year": y },
            success: function (data) {
            
                $('#setModalTitle').html("Breakage");
                $("#PanelModalBody").html(data);
             
            },
            error: function(data) {
                console.log(data);
            }

        });
    });
    $('#btnCreateBrk').click(function() {

        $.ajax({
            type: "GET",
            url: '@Url.Action("Create", "Breakages")',
            dataType: 'html',
            success: function(data) {
                console.log(data);
                $("#createBody").html(data);
                $('#createModal').modal('show');

            },
            //compelete: function(data) {
            //    $('#createModal').modal('hide');
            //}
            error: function (data) {
                console.log(data);

                alert("Create Failed");
            }
        });
    });
    
    
    $('.Detail').click(function() {
        var id = $(this).attr("rid");
        $.ajax({
            type: "GET",
            url: '@Url.Action("Details", "Breakages")',
            data: { "id": id },
            dataType: 'html',
            success: function(data) {

                $("#EditBody").html(data);
                $("#EditModal").modal('show');
            },
            error: function() {
                alert("Detail Failed");
            }
        });
    });
    $('.Edit').click(function() {
        var id = $(this).attr("rid");
        $.ajax({
            type: "GET",
            url: '@Url.Action("Edit", "Breakages")',
            data: { "id": id },
            dataType: 'html',
            success: function(data) {

                $("#EditBody").html(data);
                $('#EditModal').modal('show');
            },
            error: function() {
                alert("Edit Failed");
            }
        });
    });
    
    $('.Delete').click(function() {
        var id = $(this).attr("rid");
        $.ajax({
            type: "GET",
            url: '@Url.Action("Delete", "Breakages")',
            data: { "id": id },
            dataType: 'html',
            success: function(data) {

                $("#deleteBody").html(data);
                $('#deleteModal').modal('show');
            },
            error: function() {
                alert("Delete Failed");
            }
        });
    });
    $('#btnCloseCreate').click(function () {
        $('#createModal').modal('hide');
    });
    $('#btnCloseEdit').click(function () {
        $('#EditModal').modal('hide');
    });
    $('#btnCloseDelete').click(function () {
        $('#deleteModal').modal('hide');
    });
</script>