ENoticeBoard/ENoticeBoard/Controllers/ObjectsController.cs
using ENoticeBoard.Models;
using ENoticeBoard.ViewModels;
using System;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace ENoticeBoard.Controllers
{
    public class ObjectsController : Controller
    {
        private readonly MyDatabaseEntities _db = new MyDatabaseEntities();
        private readonly BaseDataEntities _baseData = new BaseDataEntities();
        // GET: Objects
        [HttpPost]
        public PartialViewResult Summary(string period, string year)
        {
            if(period==null && year==null)
            {
                period= DateConversion.CurrentPeriod();
                year = DateConversion.CurrentYear();
            }

            var publishedDate = DateConversion.PublishedDate();
            ViewBag.budget = _db.Targets.AsNoTracking().Single(t => t.Subject == "Budget").TargetNum;
            var model = new ObjectSummaryViewModel()
            {
                ObjectWFPs = _db.Vw_ObjectsWithinFinancialPeriod.AsNoTracking().Where(x=>x.FinancialPeriod==period && x.FinancialYear==year && x.isDeleted==false).ToList(),
                GroupByModels = _db.Vw_ObjectsWithinFinancialPeriod.AsNoTracking().Where(x=>x.FinancialPeriod==period && x.FinancialYear==year && x.isDeleted==false)
                    .GroupBy(x => new {x.FinancialPeriod, x.FinancialYear}).Select(y => new GroupByModel()
                    {
                        Period = y.Key.FinancialPeriod, Year = y.Key.FinancialYear,
                        Sum = y.Sum(z => z.Cost)
                    }).ToList(),
                Periodddl = _baseData.FinancialCalendars.AsNoTracking().Where(x=>x.Date >= publishedDate).Select(x=>new DropDownBoxList()
                {
                    text=x.FinancialPeriod,
                    value=x.FinancialPeriod
                }).Distinct().OrderBy(x=>x.value).ToList(),
                Yearddl = _baseData.FinancialCalendars.AsNoTracking().Select(x=>new DropDownBoxList()
                {
                    text=x.FinancialYear,
                    value=x.FinancialYear
                }).Distinct().OrderBy(x=>x.value).ToList(),
                SelectedPeriod = period,
                SelectedYear = year
                
            };
            return PartialView(model);
        }
        
        // GET: Objects/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Object oobject = _db.Objects.Find(id);
            if (oobject == null)
            {
                return HttpNotFound();
            }

            var model = new ObjectFormViewModel()
            {
                Id = oobject.ObjectId,
                Subject = oobject.ObjectName,
                Description = oobject.Description,
                Date = oobject.Date,
                Cost = oobject.Cost
            };
            return PartialView(model);
        }

        // GET: Objects/Create
        [HttpGet]
        public ActionResult Create()
        {
            var model = new ObjectFormViewModel
            {
                Date = DateTime.Today
            };
            return PartialView(model);
        }

        // POST: Objects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public JsonResult Create(ObjectFormViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
            }
            var @object = new Object()
            {
                ObjectId = viewModel.Id,
                ObjectName = viewModel.Subject,
                Date = viewModel.Date,
                Cost = viewModel.Cost,
                Description = viewModel.Description,
                isDeleted = false
            };
            _db.Objects.Add(@object);
            _db.SaveChanges();
            return Json("Success", JsonRequestBehavior.AllowGet);
        }

        // GET: Objects/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Object @object = _db.Objects.Find(id);
            if (@object == null)
            {
                return HttpNotFound();
            }

            var model = new ObjectFormViewModel()
            {
                Id = @object.ObjectId,
                Subject = @object.ObjectName,
                Date = @object.Date,
                Cost = @object.Cost,
                Description = @object.Description
            };
            return PartialView(model);
        }

        // POST: Objects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Edit(ObjectFormViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                Object @object = _db.Objects.Find(viewModel.Id);
                if (@object == null)
                {
                    return HttpNotFound();
                }

                @object.ObjectName = viewModel.Subject;
                @object.Date = viewModel.Date;
                @object.Cost = viewModel.Cost;
                @object.Description = viewModel.Description;

                _db.SaveChanges();

            }

            return Json("success", JsonRequestBehavior.AllowGet);
        }

        // GET: Objects/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Object @object = _db.Objects.Find(id);
        //    if (@object == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(@object);
        //}

        // POST: Objects/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Object @object = _db.Objects.Find(id);
        //    _db.Objects.Remove(@object);
        //    _db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Object @object = _db.Objects.Find(id);
            if (@object == null)
            {
                return HttpNotFound();
            }
            var model = new ObjectFormViewModel()
            {
                Id = @object.ObjectId,
                Subject = @object.ObjectName,
                Description = @object.Description,
                Date = @object.Date,
                Cost = @object.Cost
            };
            return PartialView(model);
        }

        [HttpPost]
        public JsonResult DeleteConfirmed(int? id)
        {
            Object @object = _db.Objects.Find(id);
            if (@object != null)
            {
                @object.isDeleted = true;
            }

            _db.SaveChanges();
            return Json("success", JsonRequestBehavior.AllowGet);
            
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ENoticeBoard/ENoticeBoard/Controllers/RocksController.cs
using ENoticeBoard.Models;
using ENoticeBoard.ViewModels;
using System;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace ENoticeBoard.Controllers
{
    public class RocksController : Controller
    {
        private readonly MyDatabaseEntities _db = new MyDatabaseEntities();
        private readonly BaseDataEntities _baseData = new BaseDataEntities();
        // GET: Rocks
        //public ActionResult Index()
        //{
        //    //ViewBag.objectSpend = _db.Objects.Sum(x => x.Cost);
        //    //return View(_db.Rocks.OrderByDescending(s=>s.Priority).ToList());
        //}
      

        // POST: Rocks/Create
        // To protect from over-posting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public PartialViewResult Summary(string period, string year)
        {
            if(period==null && year==null)
            {
                period = DateConversion.CurrentPeriod();
                year = DateConversion.CurrentYear();
            }

            var publishedDate = DateConversion.PublishedDate();
            var rockModel = new RockSummaryViewModel()
            {
                RockWFPs = _db.Vw_RocksWithinFinancialPeriod.AsNoTracking().Where(x=>x.FinancialPeriod==period && x.FinancialYear==year && x.isDeleted ==false  ).ToList(),
                Periodddl = _baseData.FinancialCalendars.AsNoTracking().Select(x=>new DropDownBoxList()
                {
                    text=x.FinancialPeriod,
                    value=x.FinancialPeriod
                }).Distinct().OrderBy(x=>x.value).ToList(),
                Yearddl = _baseData.FinancialCalendars.AsNoTracking().Where(x=>x.Date >= publishedDate).Select(x=>new DropDownBoxList()
                {
                    text=x.FinancialYear,
                    value=x.FinancialYear
                }).Distinct().OrderBy(x=>x.value).ToList(),
                SelectedPeriod = period,
                SelectedYear = year
            };
            
            return PartialView(rockModel);
        }


        [HttpPost]
        public JsonResult Create(String subject,int? priority, string dateDue)
        {
            DateTime dueDateInDateTime=DateTime.Parse(dateDue);
        
            if (ModelState.IsValid)
            {
                if (priority != null)
                {
                    var rock = new Rock
                    {
                        Subject = subject,
                        Priority = priority.Value,
                        DateCreated = DateTime.Today,
                        DateDue=  dueDateInDateTime,
                        Done = false,
                        isDeleted = false
                        
                    };
                    _db.Rocks.Add(rock);
                }

                _db.SaveChanges();
              
            }

            return Json("Sucess", JsonRequestBehavior.AllowGet);
        }

        // GET: Rocks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rock rock = _db.Rocks.Find(id);
            if (rock == null)
            {
                return HttpNotFound();
            }

            var model = new RockFormViewModel()
            {
                RockId = rock.RockId,
                Subject = rock.Subject,
                Priority = rock.Priority,
                DateCreated = rock.DateCreated,
                DateDue = rock.DateDue,
                Done = rock.Done
            };
            return PartialView(model);
        }

       

        // POST: Rocks/Edit/5
        // To protect from over-posting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Edit(RockFormViewModel viewModel)
        {
            
            if (ModelState.IsValid)
            {
                Rock rock = _db.Rocks.Find(viewModel.RockId);
                if (rock == null)
                {
                    return HttpNotFound();
                }

                rock.Subject = viewModel.Subject;
                rock.Priority = viewModel.Priority;
                rock.DateDue = viewModel.DateDue;
                rock.Done = viewModel.Done;
                _db.SaveChanges();
            }

            return Json("success",JsonRequestBehavior.AllowGet);
        }
        
        public ActionResult EditinSummary(int? id)
        {
            
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rock rock = _db.Rocks.Find(id);
            if (rock == null)
            {
                return HttpNotFound();
            }

            var model = new RockFormViewModel()
            {
                RockId = rock.RockId,
                Subject = rock.Subject,
                Priority = rock.Priority,
                DateDue = rock.DateDue,
                Done = rock.Done
            };
            return PartialView(model);
        }

        // GET: Breakages/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Rock rock = _db.Rocks.Find(id);
            if (rock == null)
            {
                return HttpNotFound();
            }
            
            var model = new RockFormViewModel()
            {
                RockId= rock.RockId,
                Subject = rock.Subject,
                Priority = rock.Priority,
                DateCreated = rock.DateCreated,
                DateDue = rock.DateDue,
                Done = rock.Done
            };
            

            return PartialView(model);
        }
        
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rock rock = _db.Rocks.Find(id);
            if (rock == null)
            {
                return HttpNotFound();
            }
            return PartialView(rock);
        }

        [HttpPost]
        public JsonResult DeleteConfirmed(int? id)
        {
            Rock rock = _db.Rocks.Find(id);
            if (rock != null)
            {
                rock.isDeleted = true;
            }

            _db.SaveChanges();
            return Json("success", JsonRequestBehavior.AllowGet);
            
        }


        // GET: Rocks/Done/5
        public ActionResult Done(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rock rock = _db.Rocks.Find(id);
            if (rock == null)
            {
                return HttpNotFound();
            }
            return PartialView(rock);
        }

        // POST: Rocks/Done/5
        [HttpPost, ActionName("Done")]
        [ValidateAntiForgeryToken]
        public ActionResult DoneConfirmed(int id)
        {
            var rock = _db.Rocks.AsNoTracking().FirstOrDefault(x => x.RockId == id);
            if (rock != null)
            {
                rock.Done = true;
            }

            _db.SaveChanges();
            return RedirectToAction("Index","Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }


        public JsonResult GetRocks()
        {

            var rocks = (_db.Rocks.AsNoTracking().OrderByDescending(s => s.Priority).ToList());
            return new JsonResult{Data = rocks, JsonRequestBehavior = JsonRequestBehavior.AllowGet};
            
        }
    }
}

ENoticeBoard/ENoticeBoard/Views/Objects/Create.cshtml
@using ObjectFormViewModel = ENoticeBoard.ViewModels.ObjectFormViewModel

@model ObjectFormViewModel

@{
    ViewBag.Title = "Create";
}


<form id="frmCreateObject">
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        <div class="col-md-12">
            <div class="form-group">
                @Html.LabelFor(model => model.Subject, "Object")
                @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.Date)
                @Html.TextBoxFor(model => model.Date, "{0:dd/MM/yyyy}", new { @class = "form-control", @Type = "DateTime" })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Cost)
                <div class="input-group">
                    <div class="input-group-addon">$</div>
                    @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control pull-right", @type = "number", @dir = "rtl" } })
                    @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description)
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @rows = "3" })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })

            </div>

        </div>
        <button type="button" id="btnSaveObject" value="Save" class="btn btn-success">Save</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    </div>
</form>

<script type="text/javascript">
    $('input[type=datetime]').datepicker({
        dateFormat: "dd/mm/yy",
        changeMonth: true,
        changeYear: true,
        maxDate:0,
        yearRange: "-2:+10"
    });
    $('#btnSaveObject').click(function () {
        if ($("#Subject").val().trim() === "" ||
            $("#Date").val().trim() === "" ||
            $("#Cost").val().trim() === "")
        {
            alert("All fields are required");
            return;
        }
        if ($("#Subject").val().length >100) {
            alert("Subject is too long");
            return;
        }
        if ($("#Description").val().length > 300) {
            alert("Description is too long");
            return;
        }
        else {
            var s = moment($('#Date').val(), "DD/MM/YYYY", true);
            var isValid = s.isValid();
            if (isValid === false) {
                alert("Invalid date format: " + $('#Date').val());
                return;
            }
        }
        var $this = $("#frmCreateObject");
        var dataToSend = $this.serialize();

        $.ajax({
            type: "POST",
            url: '@Url.Action("Create", "Objects")',
            dataType: 'json',
            data: dataToSend,
            success: function(data) {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Summary", "Objects")',
                    dataType: 'html',
                    success: function(data) {
                        $("#createModal").modal('hide');
                        $('#setModalTitle').html("Budget");
                        $("#PanelModalBody").html(data);
                        $("#PanelModal").modal('show');
                    },
                    error: function(data) {
                        console.log(data);
                    }
                });
            },
            error: function(data) {
                console.log(data);
            }
        });
        
    });
</script>

ENoticeBoard/ENoticeBoard/Views/Objects/Delete.cshtml
@using ObjectFormViewModel = ENoticeBoard.ViewModels.ObjectFormViewModel
@model ObjectFormViewModel

<style type="text/css">
    .dl-horizontal dt {
        text-align: left;
        width: auto;
    }

    .dl-horizontal dd {
        margin-left: 100px;
    }
</style>

<form id="frmDeleteObject">
    
    <dl class="dl-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <dt>
            Object
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Model.Date.ToShortDateString()
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

   
        

        <div class="form-group">
            <input type="button" id="btnDeleteObject" value="Delete" class="btn btn-primary" />
        </div>
    
</form>




<script>
    $('#btnDeleteObject').click(function() {
        var id = $("#Id").val();
      
     
        $.ajax({
            type: "POST",
            url: '@Url.Action("DeleteConfirmed", "Objects")',
            dataType: 'json',
            data: { "id" : id },
            success: function (data) {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Summary", "Objects")',
                    dataType: 'html',
                    success: function (data) {
                        $('#setModalTitle').html("Budget");
                        $("#PanelModalBody").html(data);
                        $("#PanelModal").modal('show');
                    },
                    error: function(data) {
                        console.log(data);
                    }
                });
                
                $('#deleteModal')
                    .modal('hide')
                    .on('hidden.bs.modal', function (e) {
                        $('#PanelModal').modal('show');

                        $(this).off('hidden.bs.modal'); // Remove the 'on' event binding
                    });
            },
            error: function(data) {
                console.log(data);
            }
        });
    });
</script>

ENoticeBoard/ENoticeBoard/Views/Objects/Edit.cshtml
@using ObjectFormViewModel = ENoticeBoard.ViewModels.ObjectFormViewModel
@model ObjectFormViewModel

@{
    ViewBag.Title = "Edit";
}




<form id="frmEditObject">
    <div class="form-horizontal">
        <div class="col-md-12">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.Subject)
                <div>
                    @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Date)
                <div>
                    @Html.TextBoxFor(model => model.Date, "{0:dd/MM/yyyy}", new { @class = "form-control", @Type = "DateTime" })
                    @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Cost)
                <div class="input-group">
                    <div class="input-group-addon">$</div>
                    @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control pull-right", @type = "number", @dir = "rtl" } })
                    @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description)
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @rows = "3" })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })

            </div>
        </div>

        <button type="button" id="btnSaveObject" value="Save" class="btn btn-success">Save</button>
        
    </div>
</form>

<script type="text/javascript">
        $('input[type=datetime]').datepicker({
            dateFormat: "dd/mm/yy",
            changeMonth: true,
            changeYear: true,
            maxDate: 0,
            yearRange: "-2:+10"
        });
    $('#btnSaveObject').click(function () {
        if ($("#Subject").val().trim() === "" ||
            $("#Date").val().trim() === "" ||
            $("#Cost").val().trim() === "")
        {
            alert("All fields are required");
            return;
        }
        if ($("#Subject").val().length >100) {
            alert("Subject is too long");
            return;
        }
        if ($("#Description").val().length > 300) {
            alert("Description is too long");
            return;
        }
        else {
            var s = moment($('#Date').val(), "DD/MM/YYYY", true);
            var isValid = s.isValid();
            if (isValid === false) {
                alert("Invalid date format: " + $('#Date').val());
                return;
            }
        }
            var $this = $("#frmEditObject");
            var dataToSend = $this.serialize();
            console.log(dataToSend);
            $.ajax({
                type: "POST",
                url: '@Url.Action("Edit", "Objects")',
                dataType: 'json',
                data: dataToSend,
                success: function () {
                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("Summary", "Objects")',
                        dataType: 'html',
                        success: function (data) {

                            $('#setModalTitle').html("Budget");
                            $("#PanelModalBody").html(data);
                            $("#PanelModal").modal('show');
                        },
                        error: function(data) {
                            console.log(data);
                        }
                    });
                    $('#EditModal')
                        .modal('hide')
                        .on('hidden.bs.modal', function () {
                            $('#PanelModal').modal('show');

                            $(this).off('hidden.bs.modal'); // Remove the 'on' event binding
                        });
                },
                error: function(data) {
                    console.log(data);
                }
            });
        });
</script>

ENoticeBoard/ENoticeBoard/Views/Objects/Index.cshtml
@model IEnumerable<ENoticeBoard.Object>


<style type="text/css">.Edit { }</style>


<button id="btnCreateObj" name="btnCreate" class="btn" style="float: left">Add</button>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ObjectName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cost)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ObjectName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cost)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                <button rid="@item.ObjectId" name="editbtn" class="btn btn-link btn-sm Edit" aria-hidden="true">
                    <span class="glyphicon glyphicon-edit"></span>
                </button>
                @Html.ActionLink("Details", "Details", new {id = item.ObjectId})

            </td>
        </tr>
    }
</table>


<div class="modal fade" id="createModal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">×</button>
                <h4 class="modal-title">Object</h4>
            </div>
            <div class="modal-body" id="createBody">
            </div>
        </div>

    </div>
</div>
<div class="modal fade" id="EditModal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">×</button>
                <h4 class="modal-title" id="myModalLabel">Object</h4>
            </div>
            <div class="modal-body" id="EditBody">
            </div>
        </div>
    </div>
</div>

<script>
    $('#btnCreateObj').click(function() {

        $.ajax({
            type: "GET",
            url: '@Url.Action("Create", "Objects")',
            dataType: 'html',
            success: function(data) {

                $("#createBody").html(data);
                $('#createModal').modal('show');

            },
            //compelete: function(data) {
            //    $('#createModal').modal('hide');
            //}
            error: function() {
                alert("Create Failed");
            }
        });
    });
    $('.DoneRock').click(function() {
        var id = $(this).attr("rid");
        $.ajax({
            type: "GET",
            url: '@Url.Action("Done", "Rocks")',
            data: { "id": id },
            dataType: 'html',
            success: function(data) {

                $("#DoneModalBody").html(data);
                $("#DoneRockModal").modal('show');
            },
            error: function() {
                alert("Done Failed");
            }
        });
    });
    $('.Edit').click(function() {
        var id = $(this).attr("rid");
        $.ajax({
            type: "GET",
            url: '@Url.Action("Edit", "Objects")',
            data: { "id": id },
            dataType: 'html',
            success: function(data) {

                $("#EditBody").html(data);
                $('#EditModal').modal('show');
            },
            error: function() {
                alert("Edit Failed");
            }
        });
    });
  
</script>