ENoticeBoard/ENoticeBoard/Controllers/DowntimesController.cs
using ENoticeBoard.Models;
using ENoticeBoard.ViewModels;
using System;
using System.Linq;
using System.Net;
using System.Web.Mvc;


namespace ENoticeBoard.Controllers
{
    public class DowntimesController : Controller
    {
        private readonly MyDatabaseEntities _db = new MyDatabaseEntities();
        private readonly BaseDataEntities _baseData = new BaseDataEntities();
        // GET: Downtimes
        [HttpPost]
        public PartialViewResult Summary(string period, string year)
        {
            if(period==null && year==null)
            {
                period= DateConversion.CurrentPeriod();
                year = DateConversion.CurrentYear();
            }

            var publishedDate = DateConversion.PublishedDate();
            ViewBag.DTPlanned = _db.Targets.AsNoTracking().Single(t => t.Subject == "Downtime_Planned").TargetNum;
            ViewBag.DTUnplanned= _db.Targets.AsNoTracking().Single(t => t.Subject == "Downtime_Unplanned").TargetNum;
            var model = new DowntimeSummaryViewModel()
            {
                DowntimeWFPs = _db.Vw_DowntimesWithinFinancialPeriod.AsNoTracking()
                    .Where(x=>x.FinancialPeriod==period && x.FinancialYear==year && x.isDeleted==false)
                    .ToList(),
                GroupByModels = _db.Vw_DowntimesWithinFinancialPeriod.AsNoTracking()
                    .Where(x=>x.FinancialPeriod==period && x.FinancialYear==year && x.isDeleted==false)
                    .GroupBy(x => new {x.FinancialPeriod, x.FinancialYear})
                    .Select(y => new GroupByModel()
                    {
                        Period = y.Key.FinancialPeriod, Year = y.Key.FinancialYear,
                        Sum = y.Sum(z => z.Duration)
                    })
                    .ToList(),
                Periodddl = _baseData.FinancialCalendars.AsNoTracking().Select(x=>new DropDownBoxList()
                {
                    text=x.FinancialPeriod,
                    value=x.FinancialPeriod
                }).Distinct().OrderBy(x=>x.value).ToList(),
                Yearddl = _baseData.FinancialCalendars.AsNoTracking().Where(x=>x.Date >= publishedDate).Select(x=>new DropDownBoxList()
                {
                    text=x.FinancialYear,
                    value=x.FinancialYear
                }).Distinct().OrderBy(x=>x.value).ToList(),
                SelectedPeriod = period,
                SelectedYear = year
                

            };
            
            return PartialView(model);
        }

        // GET: Downtimes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Downtime downtime = _db.Downtimes.Find(id);
            if (downtime == null)
            {
                return HttpNotFound();
            }

            var model = new DowntimeFormViewModel()
            {
                Id = downtime.DownTimeId,
                Subject = downtime.Subject,
                Date = downtime.Date,
                Description = downtime.Description,
                Duration = downtime.Duration,
                Type = downtime.Type,
                Types = _db.Downtimetypes.AsNoTracking().ToList(),
                Status = downtime.Status
            };
            return PartialView(model);

        }

        // GET: Downtimes/Create
        public ActionResult Create()
        {
            var model = new DowntimeFormViewModel
            {
                Date = DateTime.Today,
                Types = _db.Downtimetypes.AsNoTracking().ToList()
            };
            return PartialView(model);
        }

        // POST: Downtimes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public JsonResult Create(DowntimeFormViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                viewModel.Types = _db.Downtimetypes.AsNoTracking().ToList();
            }

            var downtime = new Downtime
            {
                DownTimeId = viewModel.Id,
                Subject = viewModel.Subject,
                Date = viewModel.Date,
                Description = viewModel.Description,
                Duration = viewModel.Duration,
                Type = viewModel.Type,
                isDeleted = false,
                Status = viewModel.Status
                
            };
            
            _db.Downtimes.Add(downtime);
            _db.SaveChanges();

            return Json("Success", JsonRequestBehavior.AllowGet);
        }

        // GET: Downtimes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Downtime downtime = _db.Downtimes.Find(id);
            if (downtime == null)
            {
                return HttpNotFound();
            }

            var model = new DowntimeFormViewModel()
            {
                Id = downtime.DownTimeId,
                Subject = downtime.Subject,
                Date = downtime.Date,
                Description = downtime.Description,
                Duration = downtime.Duration,
                Type = downtime.Type,
                Types = _db.Downtimetypes.AsNoTracking().ToList(),
                Status = downtime.Status
            };
            return PartialView(model);
        }

        // POST: Downtimes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Edit(DowntimeFormViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                Downtime downtime = _db.Downtimes.Find(viewModel.Id);
                if (downtime == null)
                {
                    return HttpNotFound();
                }

                downtime.Subject = viewModel.Subject;
                downtime.Date = viewModel.Date;
                downtime.Description = viewModel.Description;
                downtime.Duration = viewModel.Duration;
                downtime.Type = viewModel.Type;
                downtime.Status = viewModel.Status;

                _db.SaveChanges();

            }
            return Json("success", JsonRequestBehavior.AllowGet);
        }

        // GET: Downtimes/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Downtime downtime = db.Downtimes.Find(id);
        //    if (downtime == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(downtime);
        //}

        //// POST: Downtimes/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Downtime downtime = db.Downtimes.Find(id);
        //    db.Downtimes.Remove(downtime);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Downtime downtime = _db.Downtimes.Find(id);
            if (downtime == null)
            {
                return HttpNotFound();
            }
            
            var model = new DowntimeFormViewModel()
            {
                Id = downtime.DownTimeId,
                Subject = downtime.Subject,
                Date = downtime.Date,
                Description = downtime.Description,
                Duration = downtime.Duration,
                Type = downtime.Type,
                Types = _db.Downtimetypes.AsNoTracking().ToList(),
                Status = downtime.Status
            };
            return PartialView(model);

        }

        [HttpPost]
        public JsonResult DeleteConfirmed(int? id)
        {
            Downtime downtime = _db.Downtimes.Find(id);
            if (downtime != null)
            {
                downtime.isDeleted = true;
            }

            _db.SaveChanges();
            return Json("success", JsonRequestBehavior.AllowGet);
            
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ENoticeBoard/ENoticeBoard/Views/Downtimes/Create.cshtml
@using DowntimeFormViewModel = ENoticeBoard.ViewModels.DowntimeFormViewModel
@model DowntimeFormViewModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width"/>

</head>
<body>

<form id="createDT">

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        <div class="col-md-12">
            <div class="form-group">
                @Html.LabelFor(model => model.Subject)

                @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control is-valid" } })
                @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Date)

                @Html.TextBoxFor(model => model.Date, "{0:dd/MM/yyyy}", new { @class = "form-control", Type = "DateTime" })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })

            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description)
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @rows="3" } )
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })

            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Duration)
                <div class="input-group">
                    @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control pull-right", @dir="rtl" } })
                    @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
                    <div class="input-group-addon">minutes</div>
                </div>

            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Type)

                @Html.DropDownListFor(m => m.Type, new SelectList(Model.Types, "TypeId", "Subject"), "Please Select", new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Type)
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Status)
                @Html.DropDownListFor(m => m.Status, new List<SelectListItem>
                {
                    new SelectListItem {Text = "Planned", Value="Planned"},
                    new SelectListItem {Text = "Unplanned", Value="Unplanned"},
                }, "Please Select", new {@class = "form-control control-label"})
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })

            </div>
        </div>
        <button type="button" id="btnSaveDT" value="Save" class="btn btn-success">Save</button>
        
    </div>

</form>


</body>
</html>

<script type="text/javascript">
    $('input[type=datetime]').datepicker({
        dateFormat: "dd/mm/yy",
        changeMonth: true,
        changeYear: true,
        maxDate:0,
        yearRange: "-2:+10"
    });
    $('#btnSaveDT').click(function () {
        if ($("#Subject").val().trim() === "" ||
            $("#Date").val().trim() === "" ||
            $("#Description").val().trim() === "" ||
            $("#Duration").val().trim() === "" ||
            $("#Status").val().trim() === "" ||
            $("#Type").val().trim() === "") {
            alert("All fields are required");
            return;
        }
        if ($("#Subject").val().length >100) {
            alert("Subject is too long");
            return;
        }
        if ($("#Description").val().length > 300) {
            alert("Description is too long");
            return;
        }
        if ($("#Duration").val() <= 0) {
            alert("Invalid Duration: " + $("#Duration").val());
            return;
        }
        else {
            var s = moment($('#Date').val(), "DD/MM/YYYY", true);
            var isValid = s.isValid();
            if (isValid === false) {
                alert("Invalid date format: " + $('#Date').val());
                return;
            }
        }
        var $this = $("#createDT");
        var dataToSend = $this.serialize();
        console.log(dataToSend);
        $.ajax({
            type: "POST",
            url: '@Url.Action("Create", "Downtimes")',
            dataType: 'json',
            data: dataToSend,
            success: function() {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Summary", "Downtimes")',
                    dataType: 'html',
                    success: function(data) {
                        $("#createModal").modal('hide');
                        $('#setModalTitle').html("DownTime");
                        $("#PanelModalBody").html(data);
                        $("#PanelModal").modal('show');
                    },
                    error: function(data) {
                        console.log(data);
                    }
                });
                @*$.ajax({
                    type: "GET",
                    url: '@Url.Action("GetSumDowntime", "Home")',
                    dataType: 'json',
                    success: function(data) {
                        $("#DowntimeSum").html(data);
                        
                    },
                    error: function(data) {
                        console.log(data);
                    }
                });*@


            },
            error: function(data) {
                console.log(data);
            }
        });
    });
</script>

ENoticeBoard/ENoticeBoard/Views/Downtimes/Delete.cshtml
@using DowntimeFormViewModel = ENoticeBoard.ViewModels.DowntimeFormViewModel
@model DowntimeFormViewModel

<style type="text/css">
    .dl-horizontal dt {
        text-align: left;
        width: auto;
    }

    .dl-horizontal dd {
        margin-left: 100px;
    }
</style>

<div>

    <dl class="dl-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        <dt>
            @Html.DisplayNameFor(model => model.Subject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Model.Date.ToShortDateString()
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Duration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @foreach (var downtimetype in Model.Types)
            {
                if (downtimetype.TypeId == Model.Type)
                {
                    @downtimetype.Subject
                }
            }
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        <div class="form-group">
            <input type="button" id="btnDeleteDT" value="Delete" class="btn btn-primary" />

        </div>

    }
</div>

<script>
    $('#btnDeleteDT').click(function() {
        var id = $("#Id").val();


        $.ajax({
            type: "POST",
            url: '@Url.Action("DeleteConfirmed", "Downtimes")',
            dataType: 'json',
            data: { "id" : id },
            success: function (data) {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Summary", "Downtimes")',
                    dataType: 'html',
                    success: function (data) {
                        $('#setModalTitle').html("DownTime");
                        $("#PanelModalBody").html(data);
                        $("#PanelModal").modal('show');
                    },
                    error: function(data) {
                        console.log(data);
                    }
                });

                $('#deleteModal')
                    .modal('hide')
                    .on('hidden.bs.modal', function (e) {
                        $('#PanelModal').modal('show');

                        $(this).off('hidden.bs.modal'); // Remove the 'on' event binding
                    });
            },
            error: function(data) {
                console.log(data);
            }
        });
    });
</script>

ENoticeBoard/ENoticeBoard/Views/Downtimes/Edit.cshtml
@using DowntimeFormViewModel = ENoticeBoard.ViewModels.DowntimeFormViewModel
@model DowntimeFormViewModel





<form id="EditDT">

    <div class="form-horizontal">

        <div class="col-md-12">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.Subject)
                <div>
                    @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Date)
                <div>
                    @Html.TextBoxFor(model => model.Date, "{0:dd/MM/yyyy}", new { @class = "form-control", Type = "DateTime" })
                    @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description)
                <div>
                    @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @rows = "3" })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Duration)
                <div class="input-group">
                    @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control pull-right", @dir = "rtl" } })
                    @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
                    <div class="input-group-addon">minutes</div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Type)
                <div>
                    @Html.DropDownListFor(m => m.Type, new SelectList(Model.Types, "TypeId", "Subject"), "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Type)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Status)
                @Html.DropDownListFor(m => m.Status, new List<SelectListItem>
                {
                    new SelectListItem {Text = "Planned", Value = "Planned"},
                    new SelectListItem {Text = "Unplanned", Value = "Unplanned"},
                },  new {@class = "form-control control-label"})
                @Html.ValidationMessageFor(m => m.Status, "", new { @class = "text-danger" })

            </div>
        </div>
        <button type="button" id="btnSaveDT" value="Save" class="btn btn-success">Save</button>

    </div>
</form>



<script type="text/javascript">
        $('input[type=datetime]').datepicker({
            dateFormat: "dd/mm/yy",
            changeMonth: true,
            changeYear: true,
            maxDate:0,
            yearRange: "-2:+10"
        });
    $('#btnSaveDT').click(function () {
        if ($("#Subject").val().trim() === "" ||
            $("#Date").val().trim() === "" ||
            $("#Description").val().trim() === "" ||
            $("#Duration").val().trim() === "" ||
            $("#Type").val().trim() === "") {
            alert("All fields are required");
            return;
        }
        if ($("#Subject").val().length > 100) {
            alert("Subject is too long");
            return;
        }
        if ($("#Description").val().length > 300) {
            alert("Description is too long");
            return;
        }
        if ($("#Duration").val() <= 0) {
            alert("Invalid duration: " + $("#Duration").val());
            return;
        }
        else {
            var s = moment($('#Date').val(), "DD/MM/YYYY", true);
            var isValid = s.isValid();
            if (isValid === false) {
                alert("Invalid date format: " + $('#Date').val());
                return;
            }
        }
        var $this = $("#EditDT");
        var dataToSend = $this.serialize();
        $.ajax({
            type: "POST",
            url: '@Url.Action("Edit", "Downtimes")',
            dataType: 'json',
            data: dataToSend,
            success: function () {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Summary", "Downtimes")',
                    dataType: 'html',
                    success: function (data) {
                        $("#createModal").modal('hide');
                        $('#setModalTitle').html("DownTime");
                        $("#PanelModalBody").html(data);
                        $("#PanelModal").modal('show');
                    },
                    error: function(data) {
                        console.log(data);
                    }
                });
                @*$.ajax({
                    type: "GET",
                    url: '@Url.Action("GetSumDowntime", "Home")',
                    dataType: 'json',
                    success: function(data) {
                        $("#DowntimeSum").html(data);
                    },
                    error: function() {
                        alert("Set Failed");
                    }
                });*@

                $('#EditModal')
                    .modal('hide')
                    .on('hidden.bs.modal', function () {
                        $('#PanelModal').modal('show');

                        $(this).off('hidden.bs.modal'); // Remove the 'on' event binding
                    });
            },
            error: function(data) {
                console.log(data);
            }
        });
    });
</script>

ENoticeBoard/ENoticeBoard/Views/Downtimes/Summary.cshtml
@using DowntimeSummaryViewModel = ENoticeBoard.ViewModels.DowntimeSummaryViewModel
@model DowntimeSummaryViewModel


<div id="add" class="form-inline">
    <div class="pull-left">
        <div class="form-group">
            <button type="button" id="btnCreateDT" name="btnCreateDT" class="btn btn-default">
                <span class="glyphicon glyphicon-plus"></span> Add
            </button>
        </div>
    </div>
    <div class="pull-right">
        <div class="form-group">
            <label>Period: </label>
            @Html.DropDownListFor(m => m.SelectedPeriod, new SelectList(Model.Periodddl, "Text", "Value"), new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label>Year: </label>
            @Html.DropDownListFor(m => m.SelectedYear, new SelectList(Model.Yearddl, "Text", "Value"), new { @class = "form-control" })
        </div>
        <div class="form-group">
            <button type="button" id="btnRefresh" name="btnRefresh" class="btn btn-default">Refresh</button>
        </div>
    </div>

</div>

<table class="table table-bordered table-condensed  table-responsive display table-striped" id="DTTable" style="word-wrap: normal;width: 100%!important">
    <thead>
    <tr>
        <th colspan="1"> Downtime Target </th>
        <th colspan="5">Planned:
            @ViewBag.DTPlanned min -
            Unplanned:
            @ViewBag.DTUnplanned min</th>
    </tr>
    <tr>
        <th style="width: 40% !important">
            Subject
        </th>
        <th style="width: 12%">
            Date
        </th>
        <th style="width: 10%">
            Duration (min)
        </th>
        <th style="width: 10%">
            Type
        </th>
        <th>
            Status
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>

        @foreach (var item in Model.DowntimeWFPs)
        {
            <tr style="text-align: center">
                <td>
                    @Html.DisplayFor(modelItem => item.Subject)
                </td>
                <td>
                    @item.Date.ToString("dd/MM/yyyy")
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Duration)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                    @*@if (item.Description != null && item.Description.Length > 25)
                    {
                        @item.Description.Substring(0, 25)
                    }
                    else
                    {
                        @item.Description
                    }*@
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    <button rid="@item.DownTimeId" name="editbtn" class="btn btn-link btn-sm Edit" aria-hidden="true">
                        <span class="glyphicon glyphicon-edit"></span>
                    </button>
                    <button rid="@item.DownTimeId" name="detailbtn" class="btn btn-link btn-sm Detail" aria-hidden="true">
                        <span class="glyphicon glyphicon-eye-open"></span>
                    </button>
                    <button rid="@item.DownTimeId" name="deletebtn" class="btn btn-link btn-sm Delete" aria-hidden="true">
                        <span class="glyphicon glyphicon-trash"></span>
                    </button>
                </td>
            </tr>
       
    }
    </tbody>
</table>

<div class="modal fade" id="createModal" role="dialog">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" id="btnCloseCreate">×</button>
                <h4 class="modal-title">Downtime</h4>
            </div>
            <div class="modal-body" id="createBody">
            </div>
        </div>

    </div>
</div>
<div class="modal fade" id="EditModal" role="dialog">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" id="btnCloseEdit">×</button>
                <h4 class="modal-title" id="myModalLabel">Downtime</h4>
            </div>
            <div class="modal-body" id="EditBody">
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="deleteModal" role="dialog">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" id="btnCloseDelete">×</button>
                <h4 class="modal-title">You want to delete this task?</h4>
            </div>
            <div class="modal-body" id="deleteBody">
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready( function () {
        $('#DTTable').DataTable({
            autoWidth: false,
            columns: [
                { "width": "40%" },
                { "width": "12%" },
                { "width": "10%" },
                { "width": "10%" },
                null,
                null
            ],
            aoColumnDefs: [
                { "aTargets": [1], "sType": "date-uk" }
            ]
        });

    });
    
    $('#btnRefresh').click(function() {
        var p = $("#SelectedPeriod").val();
        var y = $('#SelectedYear').val();
       
        $.ajax({
            type: "POST",
            url: '@Url.Action("Summary","Downtimes")',
            datatype: "html",
            data: { "period": p, "year": y },
            success: function (data) {
            
                $('#setModalTitle').html("DownTime");
                $("#PanelModalBody").html(data);
             
            },
            error: function(data) {
                console.log(data);
            }

        });
    });
    $('#btnCreateDT').click(function() {

        $.ajax({
            type: "GET",
            url: '@Url.Action("Create", "Downtimes")',
            dataType: 'html',
            success: function(data) {

                $("#createBody").html(data);
                $('#createModal').modal('show');

            },
            //compelete: function(data) {
            //    $('#createModal').modal('hide');
            //}
            error: function() {
                alert("Create Failed");
            }
        });
    });
    $('.Detail').click(function() {
        var id = $(this).attr("rid");
        $.ajax({
            type: "GET",
            url: '@Url.Action("Details", "Downtimes")',
            data: { "id": id },
            dataType: 'html',
            success: function(data) {

                $("#EditBody").html(data);
                $("#EditModal").modal('show');
            },
            error: function() {
                alert("Detail Failed");
            }
        });
    });
    $('.Edit').click(function() {
        var id = $(this).attr("rid");
        $.ajax({
            type: "GET",
            url: '@Url.Action("Edit", "Downtimes")',
            data: { "id": id },
            dataType: 'html',
            success: function(data) {

                $("#EditBody").html(data);
                $('#EditModal').modal('show');
            },
            error: function() {
                alert("Edit Failed");
            }
        });
    });
    $('.Delete').click(function() {
        var id = $(this).attr("rid");
        $.ajax({
            type: "GET",
            url: '@Url.Action("Delete", "Downtimes")',
            data: { "id": id },
            dataType: 'html',
            success: function(data) {

                $("#deleteBody").html(data);
                $('#deleteModal').modal('show');
            },
            error: function() {
                alert("Delete Failed");
            }
        });
    });
    $('#btnCloseCreate').click(function () {
        $('#createModal').modal('hide');
    });
    $('#btnCloseEdit').click(function () {
        $('#EditModal').modal('hide');
    });
    $('#btnCloseDelete').click(function () {
        $('#deleteModal').modal('hide');
    });
</script>